version: '3'
services:
  data-capture:
    build: ./Lab.DataCapture
    container_name: data-capture-service
    hostname: 10.15.1.3
    environment:
      - "EUREKA_SERVER=http://khoa:welcome123@10.15.1.1:18761/eureka"
      - "EUREKA_CONFIG_SERVER=http://10.15.1.2:11512"
      - "server.port=11513"
    networks:
      labdiscoveryservice_microservice:
        ipv4_address: 10.15.1.3
      cluster1_cassandra-network:
    expose:
     - "11513"
     
  cassandra:
    build: ./Lab.Cassandra
    container_name: cassandra-service
    hostname: 10.15.1.4
    environment:
      - "EUREKA_SERVER=http://khoa:welcome123@10.15.1.1:18761/eureka"
      - "EUREKA_CONFIG_SERVER=http://10.15.1.2:11512"
      - "server.port=11514"
    networks:
      labdiscoveryservice_microservice:
        ipv4_address: 10.15.1.4
      cluster1_cassandra-network:
    expose:
      - "11514"
      
  ui:
    build: ./Lab.UI
    container_name: ui-service
    hostname: 10.15.1.5
    environment:
      - "EUREKA_SERVER=http://khoa:welcome123@10.15.1.1:18761/eureka"
      - "EUREKA_CONFIG_SERVER=http://10.15.1.2:11512"
      - "server.port=11515"
    networks:
      labdiscoveryservice_microservice:
        ipv4_address: 10.15.1.5
      cluster1_cassandra-network:
    ports:
      - 11515:11515
    volumes:
      - /tmp:/home/khoa
    expose:
      - "11515"
      
networks:
  labdiscoveryservice_microservice:
    external: true
  cluster1_cassandra-network:
    external: true
