version: '3'
services:
      
  kafka:
    build: ./Lab.Kafka
    container_name: kafka-service
    hostname: 10.15.1.6
    environment:
      - "EUREKA_SERVER=http://khoa:welcome123@10.15.1.1:18761/eureka"
      - "EUREKA_CONFIG_SERVER=http://10.15.1.2:11512"
      - "server.port=11516"
    networks:
      aaa_lab_network_10_x:
        ipv4_address: 10.15.1.6
    ports:
      - 11516:11516
      - 4446:4444
    volumes:
      - /tmp:/home/khoa
    expose:
      - "11516"
      
  spark:
    build: ./Lab.Spark
    container_name: spark-service
    hostname: 10.15.1.7
    environment:
      - "EUREKA_SERVER=http://khoa:welcome123@10.15.1.1:18761/eureka"
      - "EUREKA_CONFIG_SERVER=http://10.15.1.2:11512"
      - "server.port=11517"
    networks:
      aaa_lab_network_10_x:
        ipv4_address: 10.15.1.7
    ports:
      - 11517:11517
      - 4447:4444
    volumes:
      - /tmp:/home/khoa
      - /home/khoa/git/spark-docker-setup/data:/opt/spark-data
    expose:
      - "11517"
      
networks:
  aaa_lab_network_10_x:
    external: true