version: '3'
services:
  config:
    build: ./Lab.ServiceConfiguration
    environment:
      - JVM_OPTS=""
      - "EUREKA_SERVER=http://discovery:18761/eureka"
    networks:
      labdiscoveryservice_microservice-network:
        ipv4_address: 10.15.1.2
    ports:
      - 8888:8888
      
networks:
  labdiscoveryservice_microservice-network:
    external: true