version: '3'
services:
  config:
    build: ./Lab.ServiceConfiguration
    environment:
      - "EUREKA_SERVER=http://10.15.1.1:18761/eureka"
    networks:
      labdiscoveryservice_microservice:
        ipv4_address: 10.15.1.2
    ports:
      - 8888:8888
      
networks:
  labdiscoveryservice_microservice:
    external: true