version: '3'
services:
  config:
    build: ./Lab.ServiceConfiguration
    container_name: service-configuration
    hostname: service-configuration
    environment:
      - "EUREKA_SERVER=http://10.15.1.1:18761/eureka"
    networks:
      labdiscoveryservice_microservice:
        ipv4_address: 10.15.1.2
    ports:
      - 101512:101512
  data-capture:
    build: ./Lab.DataCapture
    container_name: data-capture
    hostname: data-capture
    environment:
      - "EUREKA_SERVER=http://10.15.1.1:18761/eureka"
    networks:
      labdiscoveryservice_microservice:
        ipv4_address: 10.15.1.3
    ports:
      - 101513:101513
      
networks:
  labdiscoveryservice_microservice:
    external: true