version: '3'
services:
  config:
    build: ./Lab.ServiceConfiguration
    container_name: configuration-service
    hostname: 10.15.1.2
    environment:
      - "EUREKA_SERVER=http://khoa:welcome123@10.15.1.1:18761/eureka"
    networks:
      labdiscoveryservice_microservice:
        ipv4_address: 10.15.1.2
    ports:
      - 11512:11512
  data-capture:
    build: ./Lab.DataCapture
    container_name: data-capture-service
    hostname: 10.15.1.3
    environment:
      - "EUREKA_SERVER=http://khoa:welcome123@10.15.1.1:18761/eureka"
      - "server.port=11513"
    networks:
      labdiscoveryservice_microservice:
        ipv4_address: 10.15.1.3
    ports:
      - 11513:11513
  cassandra:
    build: ./Lab.Cassandra
    container_name: cassandra-service
    hostname: 10.15.1.4
    environment:
      - "EUREKA_SERVER=http://khoa:welcome123@10.15.1.1:18761/eureka"
      - "server.port=11514"
    networks:
      labdiscoveryservice_microservice:
        ipv4_address: 10.15.1.4
    ports:
      - 11514:11514
      
networks:
  labdiscoveryservice_microservice:
    external: true